CREATE TABLE IF NOT EXISTS post (
  id INTEGER PRIMARY KEY AUTOINCREMENT ,
  title TEXT NOT NULL,
  url TEXT(150)
);

CREATE TABLE IF NOT EXISTS user_post (
    chat_id INTEGER NOT NULL,
    post INTEGER,
    checked INTEGER DEFAULT 0,
    FOREIGN KEY (post) REFERENCES post(id) ON DELETE CASCADE
);